name: CI
on:
  push:

jobs:
  build-rust:
    name: Build Rust
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src

      - name: Cache Rust Dependencies
        uses: ./.github/actions/rust-cache
        with:
          key: rust-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            rust-${{ runner.os }}
      
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
  
  build-rust-2:
    name: Build Rust 2
    runs-on: ubuntu-latest
    needs: [build-rust]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src

      - name: Cache Rust Dependencies
        uses: ./.github/actions/rust-cache
        with:
          key: rust-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            rust-${{ runner.os }}
      
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release